//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXON.RegisterManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EXON.RegisterManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã Phê Duyệt.
        /// </summary>
        internal static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Actions_list_add_icon__1_ {
            get {
                object obj = ResourceManager.GetObject("Actions-list-add-icon (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add16 {
            get {
                object obj = ResourceManager.GetObject("add16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu Trả Lời.
        /// </summary>
        internal static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi Mật Khẩu.
        /// </summary>
        internal static string bbiChangePassword {
            get {
                return ResourceManager.GetString("bbiChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng Kí.
        /// </summary>
        internal static string bbiDangKi {
            get {
                return ResourceManager.GetString("bbiDangKi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        internal static string bbiLogout {
            get {
                return ResourceManager.GetString("bbiLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công Việc.
        /// </summary>
        internal static string bbiMyTaskDescription {
            get {
                return ResourceManager.GetString("bbiMyTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đề Thi Gốc .
        /// </summary>
        internal static string bbiOriginalTestDescription {
            get {
                return ResourceManager.GetString("bbiOriginalTestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo Câu Hỏi.
        /// </summary>
        internal static string bbiQuestionDescription {
            get {
                return ResourceManager.GetString("bbiQuestionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo Loại Câu Hỏi.
        /// </summary>
        internal static string bbiQuestionTypeDescription {
            get {
                return ResourceManager.GetString("bbiQuestionTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu Trúc Đề.
        /// </summary>
        internal static string bbiStructureTestDescription {
            get {
                return ResourceManager.GetString("bbiStructureTestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân Công.
        /// </summary>
        internal static string bbiTaskDescription {
            get {
                return ResourceManager.GetString("bbiTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinh Đề Thi.
        /// </summary>
        internal static string bbiTestDescription {
            get {
                return ResourceManager.GetString("bbiTestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thí Sinh.
        /// </summary>
        internal static string bbiThiSinh {
            get {
                return ResourceManager.GetString("bbiThiSinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ Đề Môn Học.
        /// </summary>
        internal static string bbiTopicDescription {
            get {
                return ResourceManager.GetString("bbiTopicDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap check16 {
            get {
                object obj = ResourceManager.GetObject("check16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn Thành.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete16 {
            get {
                object obj = ResourceManager.GetObject("delete16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete161 {
            get {
                object obj = ResourceManager.GetObject("delete161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuestionTypeName.
        /// </summary>
        internal static string DisplayMemberQuestionType {
            get {
                return ResourceManager.GetString("DisplayMemberQuestionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubjectName.
        /// </summary>
        internal static string DisplayMemberSubject {
            get {
                return ResourceManager.GetString("DisplayMemberSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopicName.
        /// </summary>
        internal static string DisplayMemberTopic {
            get {
                return ResourceManager.GetString("DisplayMemberTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang Thực Hiện.
        /// </summary>
        internal static string During {
            get {
                return ResourceManager.GetString("During", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tự Luận.
        /// </summary>
        internal static string Essay {
            get {
                return ResourceManager.GetString("Essay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Excel_icon {
            get {
                object obj = ResourceManager.GetObject("Excel-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exl16 {
            get {
                object obj = ResourceManager.GetObject("exl16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap filter {
            get {
                object obj = ResourceManager.GetObject("filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arial.
        /// </summary>
        internal static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã Có Đề Thi Gốc. Bạn Có Muốn Tạo Thêm Không?.
        /// </summary>
        internal static string HaveOriginalTestMessage {
            get {
                return ResourceManager.GetString("HaveOriginalTestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Mới.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ Khó.
        /// </summary>
        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mức Nhận Biết.
        /// </summary>
        internal static string Level1 {
            get {
                return ResourceManager.GetString("Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mức Thông Hiểu.
        /// </summary>
        internal static string Level2 {
            get {
                return ResourceManager.GetString("Level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mức Vận Dụng.
        /// </summary>
        internal static string Level3 {
            get {
                return ResourceManager.GetString("Level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mức Vận Dụng Cao.
        /// </summary>
        internal static string Level4 {
            get {
                return ResourceManager.GetString("Level4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh Sách Kỳ Thi.
        /// </summary>
        internal static string ListContest {
            get {
                return ResourceManager.GetString("ListContest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo Đề Thi Gốc Với Số Lượng.
        /// </summary>
        internal static string MakeOriginalTestWithNum {
            get {
                return ResourceManager.GetString("MakeOriginalTestWithNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa Thành Công.
        /// </summary>
        internal static string MessageDeleteSuccess {
            get {
                return ResourceManager.GetString("MessageDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mới.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không Thể Kết Nối Server.
        /// </summary>
        internal static string NotConnectServerMessage {
            get {
                return ResourceManager.GetString("NotConnectServerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa Có Thí Sinh Thi.
        /// </summary>
        internal static string NotContestainMessage {
            get {
                return ResourceManager.GetString("NotContestainMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa Đến Hoặc Quá Hạn Tạo Đề.
        /// </summary>
        internal static string NotDuringTestMessage {
            get {
                return ResourceManager.GetString("NotDuringTestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không Đủ Câu Hỏi.
        /// </summary>
        internal static string NotEnoughQuestionMessage {
            get {
                return ResourceManager.GetString("NotEnoughQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông Báo.
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn Nhập Thiếu.
        /// </summary>
        internal static string NotInputMessage {
            get {
                return ResourceManager.GetString("NotInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật Khẩu Sai Hoặc Tài Khoản Không Tồn Tại.
        /// </summary>
        internal static string NotLoginMessage {
            get {
                return ResourceManager.GetString("NotLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa Có Đề Thi Gốc Được Hoặc Chưa Được Phê Duyệt.\n Tạo Đề Thi Gốc Trước..
        /// </summary>
        internal static string NotOriginalTestMessage {
            get {
                return ResourceManager.GetString("NotOriginalTestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa Có Dữ Liệu Câu Hỏi.
        /// </summary>
        internal static string NotQuestionMessage {
            get {
                return ResourceManager.GetString("NotQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn Một Dòng.
        /// </summary>
        internal static string NotRowMessage {
            get {
                return ResourceManager.GetString("NotRowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa Có Lịch Thi.
        /// </summary>
        internal static string NotScheduleMessage {
            get {
                return ResourceManager.GetString("NotScheduleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa Chọn Kiểu Câu Hỏi.
        /// </summary>
        internal static string NotSelectQuestionTypeMessage {
            get {
                return ResourceManager.GetString("NotSelectQuestionTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn Chưa Chọn Người Nhận.
        /// </summary>
        internal static string NotSelectStaff {
            get {
                return ResourceManager.GetString("NotSelectStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa Chọn Chủ Đề.
        /// </summary>
        internal static string NotSelectStaffMessage {
            get {
                return ResourceManager.GetString("NotSelectStaffMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa Có Cấu Trúc Đề.
        /// </summary>
        internal static string NotStructureMessage {
            get {
                return ResourceManager.GetString("NotStructureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo Đề Thi Gốc Thành Công, Bấm Xem Đề Thi Để Xem Chi Tiết.
        /// </summary>
        internal static string OriginalTestCreateSuccess {
            get {
                return ResourceManager.GetString("OriginalTestCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quá Hạn.
        /// </summary>
        internal static string Over {
            get {
                return ResourceManager.GetString("Over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui Lòng Chờ.
        /// </summary>
        internal static string ProgressPanelCaption {
            get {
                return ResourceManager.GetString("ProgressPanelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ....
        /// </summary>
        internal static string ProgressPanelDescription {
            get {
                return ResourceManager.GetString("ProgressPanelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu Hỏi.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đoạn Văn.
        /// </summary>
        internal static string QuestionContent {
            get {
                return ResourceManager.GetString("QuestionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu Hỏi.
        /// </summary>
        internal static string QuestionName {
            get {
                return ResourceManager.GetString("QuestionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trắc Nghiệm.
        /// </summary>
        internal static string Quiz {
            get {
                return ResourceManager.GetString("Quiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh162 {
            get {
                object obj = ResourceManager.GetObject("refresh162", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không được để trống.
        /// </summary>
        internal static string RuleIsNotBlankWarning {
            get {
                return ResourceManager.GetString("RuleIsNotBlankWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Quá Dài.
        /// </summary>
        internal static string RulelsTooMuchLenght {
            get {
                return ResourceManager.GetString("RulelsTooMuchLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search16 {
            get {
                object obj = ResourceManager.GetObject("search16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search24 {
            get {
                object obj = ResourceManager.GetObject("search24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bấm Xem Đề Thi Để Xem Chi Tiết.
        /// </summary>
        internal static string ShowOriginalMessage {
            get {
                return ResourceManager.GetString("ShowOriginalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày Giờ Bắt Đầu Không Được Nhỏ Hơn Hiện Tại.
        /// </summary>
        internal static string SmallDateMessage {
            get {
                return ResourceManager.GetString("SmallDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày Giờ Kết Thúc Không Được Nhỏ Hơn Bắt Đầu.
        /// </summary>
        internal static string SmallDateStartMessage {
            get {
                return ResourceManager.GetString("SmallDateStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu Trúc Đề Thi.
        /// </summary>
        internal static string StructureTestName {
            get {
                return ResourceManager.GetString("StructureTestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Môn Học.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành Công.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại Câu Hỏi .
        /// </summary>
        internal static string TypeQuestionName {
            get {
                return ResourceManager.GetString("TypeQuestionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu Thay Đổi.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuestionTypeID.
        /// </summary>
        internal static string ValueMemberQuestionType {
            get {
                return ResourceManager.GetString("ValueMemberQuestionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubjectID.
        /// </summary>
        internal static string ValueMemberSubject {
            get {
                return ResourceManager.GetString("ValueMemberSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopicID.
        /// </summary>
        internal static string ValueMemberTopic {
            get {
                return ResourceManager.GetString("ValueMemberTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảnh Báo.
        /// </summary>
        internal static string WarningDialog {
            get {
                return ResourceManager.GetString("WarningDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem Đề Thi.
        /// </summary>
        internal static string WatchOriginalTest {
            get {
                return ResourceManager.GetString("WatchOriginalTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn Đã Chắc Chắn Chưa?.
        /// </summary>
        internal static string YesNoMessage {
            get {
                return ResourceManager.GetString("YesNoMessage", resourceCulture);
            }
        }
    }
}
