//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoiDongThiVer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIVISION_SHIFTS
    {
        public DIVISION_SHIFTS()
        {
            this.BAGOFTESTS = new HashSet<BAGOFTEST>();
            this.CONTESTANTS_SHIFTS = new HashSet<CONTESTANTS_SHIFTS>();
            this.DIVISIONSHIFT_SUPERVISOR = new HashSet<DIVISIONSHIFT_SUPERVISOR>();
        }
    
        public int DivisionShiftID { get; set; }
        public int Status { get; set; }
        public int ShiftID { get; set; }
        public int RoomTestID { get; set; }
        public string Key { get; set; }
    
        public virtual ICollection<BAGOFTEST> BAGOFTESTS { get; set; }
        public virtual ICollection<CONTESTANTS_SHIFTS> CONTESTANTS_SHIFTS { get; set; }
        public virtual ICollection<DIVISIONSHIFT_SUPERVISOR> DIVISIONSHIFT_SUPERVISOR { get; set; }
        public virtual ROOMTEST ROOMTEST { get; set; }
        public virtual SHIFT SHIFT { get; set; }
    }
}
