//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoiDongThiVer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTIONS_TEMP
    {
        public int QuestionID { get; set; }
        public string QuestionContent { get; set; }
        public Nullable<int> QuestionFormat { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<bool> IsQuiz { get; set; }
        public Nullable<bool> IsSingleChoice { get; set; }
        public Nullable<bool> IsParagarph { get; set; }
        public Nullable<bool> IsQuestionContent { get; set; }
        public Nullable<int> NumberSubQuestion { get; set; }
        public Nullable<int> NumberAnswer { get; set; }
        public Nullable<int> DivisionShiftID { get; set; }
        public int QuestionTempID { get; set; }
    }
}
