//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoiDongThiVer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOMTEST
    {
        public ROOMTEST()
        {
            this.DIVISION_SHIFTS = new HashSet<DIVISION_SHIFTS>();
            this.ROOMDIAGRAMS = new HashSet<ROOMDIAGRAM>();
        }
    
        public int RoomTestID { get; set; }
        public string RoomTestName { get; set; }
        public int MaxSeatMount { get; set; }
        public Nullable<int> MaxSupervisor { get; set; }
        public int Status { get; set; }
        public int LocationID { get; set; }
    
        public virtual ICollection<DIVISION_SHIFTS> DIVISION_SHIFTS { get; set; }
        public virtual LOCATION LOCATION { get; set; }
        public virtual ICollection<ROOMDIAGRAM> ROOMDIAGRAMS { get; set; }
    }
}
