//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoiDongThiVer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF
    {
        public STAFF()
        {
            this.ANSWERSHEETS = new HashSet<ANSWERSHEET>();
            this.DIVISIONSHIFT_SUPERVISOR = new HashSet<DIVISIONSHIFT_SUPERVISOR>();
            this.EXAMINATIONCOUNCIL_STAFFS = new HashSet<EXAMINATIONCOUNCIL_STAFFS>();
            this.STAFFS_POSITIONS = new HashSet<STAFFS_POSITIONS>();
        }
    
        public int StaffID { get; set; }
        public string FullName { get; set; }
        public Nullable<int> DOB { get; set; }
        public Nullable<int> Sex { get; set; }
        public string IdentityCardNumber { get; set; }
        public string AcademicRank { get; set; }
        public string Degree { get; set; }
        public int Status { get; set; }
    
        public virtual ICollection<ANSWERSHEET> ANSWERSHEETS { get; set; }
        public virtual ICollection<DIVISIONSHIFT_SUPERVISOR> DIVISIONSHIFT_SUPERVISOR { get; set; }
        public virtual ICollection<EXAMINATIONCOUNCIL_STAFFS> EXAMINATIONCOUNCIL_STAFFS { get; set; }
        public virtual ICollection<STAFFS_POSITIONS> STAFFS_POSITIONS { get; set; }
    }
}
