//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHoiDongThiVer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST
    {
        public TEST()
        {
            this.CONTESTANTS_TESTS = new HashSet<CONTESTANTS_TESTS>();
            this.TEST_DETAILS = new HashSet<TEST_DETAILS>();
        }
    
        public int TestID { get; set; }
        public int Status { get; set; }
        public int BagOfTestID { get; set; }
        public int SubjectID { get; set; }
    
        public virtual BAGOFTEST BAGOFTEST { get; set; }
        public virtual ICollection<CONTESTANTS_TESTS> CONTESTANTS_TESTS { get; set; }
        public virtual SUBJECT SUBJECT { get; set; }
        public virtual ICollection<TEST_DETAILS> TEST_DETAILS { get; set; }
    }
}
