//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTESTANTS_SHIFTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTESTANTS_SHIFTS()
        {
            this.CONTESTANTS_TESTS = new HashSet<CONTESTANTS_TESTS>();
            this.VIOLATIONS_CONTESTANTS = new HashSet<VIOLATIONS_CONTESTANTS>();
        }
    
        public int ContestantShiftID { get; set; }
        public int Status { get; set; }
        public Nullable<int> IsCheckFingerprint { get; set; }
        public Nullable<int> TimeCheck { get; set; }
        public Nullable<int> TimeStarted { get; set; }
        public Nullable<int> TimeWorked { get; set; }
        public int DivisionShiftID { get; set; }
        public int ScheduleID { get; set; }
        public int ContestantID { get; set; }
        public Nullable<int> RoomDiagramID { get; set; }
    
        public virtual CONTESTANT CONTESTANT { get; set; }
        public virtual ROOMDIAGRAM ROOMDIAGRAM { get; set; }
        public virtual SCHEDULE SCHEDULE { get; set; }
        public virtual DIVISION_SHIFTS DIVISION_SHIFTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTESTANTS_TESTS> CONTESTANTS_TESTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIOLATIONS_CONTESTANTS> VIOLATIONS_CONTESTANTS { get; set; }
    }
}
