//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTESTANT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTESTANT()
        {
            this.CONTESTANTS_SHIFTS = new HashSet<CONTESTANTS_SHIFTS>();
            this.FINGERPRINTS = new HashSet<FINGERPRINT>();
        }
    
        public int ContestantID { get; set; }
        public string ContestantCode { get; set; }
        public string ContestantType { get; set; }
        public string FullName { get; set; }
        public Nullable<int> DOB { get; set; }
        public string Ethnic { get; set; }
        public string PlaceOfBirth { get; set; }
        public string HighSchool { get; set; }
        public Nullable<int> Sex { get; set; }
        public string IdentityCardNumber { get; set; }
        public string Unit { get; set; }
        public string CurrentAddress { get; set; }
        public string TrainingSystem { get; set; }
        public string StudentCode { get; set; }
        public byte[] Image { get; set; }
        public int Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTESTANTS_SHIFTS> CONTESTANTS_SHIFTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FINGERPRINT> FINGERPRINTS { get; set; }
    }
}
