//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIVISIONSHIFT_SUPERVISOR
    {
        public int DivisionShift_SupervisorID { get; set; }
        public Nullable<int> SupervisorID { get; set; }
        public Nullable<int> DivisionShiftID { get; set; }
    
        public virtual DIVISION_SHIFTS DIVISION_SHIFTS { get; set; }
        public virtual STAFF STAFF { get; set; }
    }
}
