//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINGERPRINT
    {
        public int FingerprintID { get; set; }
        public byte[] FingerprintImage { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> TimeSaveFingerprint { get; set; }
        public int Status { get; set; }
        public int ContestantID { get; set; }
    
        public virtual CONTESTANT CONTESTANT { get; set; }
    }
}
