//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCHEDULE()
        {
            this.CONTESTANTS_SHIFTS = new HashSet<CONTESTANTS_SHIFTS>();
        }
    
        public int ScheduleID { get; set; }
        public int TimeOfTest { get; set; }
        public int TimeToSubmit { get; set; }
        public int Status { get; set; }
        public Nullable<int> ContestID { get; set; }
        public string ContestTypeName { get; set; }
        public int SubjectID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTESTANTS_SHIFTS> CONTESTANTS_SHIFTS { get; set; }
        public virtual SUBJECT SUBJECT { get; set; }
    }
}
