//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIFT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SHIFT()
        {
            this.DIVISION_SHIFTS = new HashSet<DIVISION_SHIFTS>();
        }
    
        public int ShiftID { get; set; }
        public string ShiftName { get; set; }
        public int ShiftDate { get; set; }
        public int StartTime { get; set; }
        public int EndTime { get; set; }
        public int Status { get; set; }
        public Nullable<int> ContestID { get; set; }
    
        public virtual CONTEST CONTEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIVISION_SHIFTS> DIVISION_SHIFTS { get; set; }
    }
}
