//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFFS_POSITIONS
    {
        public int StaffPositionID { get; set; }
        public int StaffID { get; set; }
        public int PositionID { get; set; }
    
        public virtual POSITION POSITION { get; set; }
        public virtual STAFF STAFF { get; set; }
    }
}
