//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBQUESTIONS_TEMP
    {
        public int SubQuestionID { get; set; }
        public string SubQuestionContent { get; set; }
        public Nullable<double> Score { get; set; }
        public int QuestionID { get; set; }
        public Nullable<int> QuestionTempID { get; set; }
        public int DivisionShiftID { get; set; }
        public int SubQuestionTempID { get; set; }
    }
}
