//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_DETAILS
    {
        public int TestDetailID { get; set; }
        public string RandomAnswer { get; set; }
        public int NumberIndex { get; set; }
        public double Score { get; set; }
        public int Status { get; set; }
        public int TestID { get; set; }
        public int QuestionID { get; set; }
    
        public virtual QUESTION QUESTION { get; set; }
        public virtual TEST TEST { get; set; }
    }
}
