//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIOLATIONS_CONTESTANTS
    {
        public int ViolationDetailID { get; set; }
        public int Status { get; set; }
        public Nullable<int> TimeSave { get; set; }
        public int ViolationID { get; set; }
        public int ContestantShiftID { get; set; }
    
        public virtual CONTESTANTS_SHIFTS CONTESTANTS_SHIFTS { get; set; }
        public virtual VIOLATION VIOLATION { get; set; }
    }
}
